name: 📦 Update Repo List

on:
  schedule:
    - cron: "0 * * * *"  # Tiap 1 jam
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install requirements
        run: pip install requests python-dotenv

      - name: Run script
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: python gen_repo_list.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add LISTREPO.md
          git commit -m "📝 auto-update repo list" || echo "No changes to commit"
          git push
